[project]
name = "03-rag-read-from-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.13.0",
    "ipykernel>=6.29.5",
    "langchain>=0.3.25",
    "langchain-chroma>=0.2.6",
    "langchain-community>=0.3.25",
    "langchain-ollama>=0.3.3",
    "langchain-openai>=0.3.35",
    "openai>=2.8.1",
    "pypdf>=5.6.0",
    "python-decouple>=3.8",
    "sentence-transformers>=5.1.2",
    "vector-db-1807>=0.3.0",
]
